import React from 'react';
import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiRedux,
  SiReactquery,
  SiGit,
  SiWebpack,
  SiVite,
  SiNpm,
  SiFigma,
  SiVscodium,
  SiNextdotjs,
  SiStyledcomponents,
  SiTailwindcss,
  SiSass,
  SiVercel,
  SiReacthookform,
  SiGithub,
  SiGmail,
  SiVelog
} from 'react-icons/si';

export const iconMap: Record<string, React.ReactNode> = {
  'React': <SiReact color="#61DAFB" />,
  'TypeScript': <SiTypescript color="#3178C6" />,
  'JavaScript': <SiJavascript color="#F7DF1E" />,
  'HTML5': <SiHtml5 color="#E34F26" />,
  'CSS3': <SiCss3 color="#1572B6" />,
  'Redux': <SiRedux color="#764ABC" />,
  'React Query': <SiReactquery color="#FF4154" />,
  'Zustand': <span style={{ fontSize: '24px' }}>🐻</span>,
  'Context API': <SiReact color="#61DAFB" />,
  'Git': <SiGit color="#F05032" />,
  'Webpack': <SiWebpack color="#8DD6F9" />,
  'Vite': <SiVite color="#646CFF" />,
  'npm': <SiNpm color="#CB3837" />,
  'Figma': <SiFigma color="#F24E1E" />,
  'VS Code': <SiVscodium color="#007ACC" />,
  'Next.js': <SiNextdotjs color="#000000" />,
  'Styled Components': <SiStyledcomponents color="#DB7093" />,
  'Tailwind CSS': <SiTailwindcss color="#06B6D4" />,
  'Sass': <SiSass color="#CC6699" />,
  'Vercel': <SiVercel color="#000000" />,
  'React Hook Form': <SiReacthookform color="#EC5990" />,
};
